---
title: "Automate"
author: "Rob Hayward"
date: "26 December 2015"
output: 
  html_document: 
    highlight: kate
    number_sections: yes
    theme: united
    toc: yes
---

#Introduction

There are two methods

* Interactive shell 
* Text editor

There are different classes

* integer
* floating points
* strings

There are 

* Statements
* Expressions (evaluates)

Objects can be switched from one class to another. For example, 

* str(26)
* int(124)
* float(1)

##Boolean operators

Operator|Evaluates to
--------|------
True and True| True
True and False| False
False and True| False
False and False| False

Operator|Evaluates to 
--------|-----------
True or True|True
True or False|True
False or True|True
False or False|False

Operator|Evaluates to 
------|------
Not True|False
Not False|True

## Control statements
Programmes can be evaluated at [Python Tutor](https://pythontutor.com/visualize.html). Blocks of code are determined by indentation.  

Order of the `if...elif` statements is important.  The first true will be activated. The values 0, 0.0 and the empty string are considered false values. You can check with `bool()`.

If there is an infinite loop, CNTR-C will end. `break` can also be used to break the programme. `continue`  can also be used within a loop. 

`range` is an object that will run from first to last number.  For example, `range(2, 4)` will run from 2 to 4.  Third argument would be the step function. 

#Functions
Each python instillation comes with a group of modules or built in functions. For example, the `math` module has maths functions and the `rand` module has functions for random variables. `import`  will import the module. 

```
import(rand)
random.randint(0, 1)
```

If you type, 
```
from rand import *
```

This will import all the functions from the random module. Now it is not necessary to type rand. before the function.  There are modules with the standard library but also third party libraries.  These are imported with `pip`. 

## Writing own functions
`def` is used to define a function. 

```
def hello():
    print('Howdy')
    print('Howdy!!')
    print('Howdy!!!')

hello()
hello()
hello()
```

Functions aim to remove the need to duplicate. 

* The function will take *arguments* that are specified by the user. They are called *parameters* when they are given in the function. Function calls can be part of expressions because they evaluate to a value returned by the function call. When creating a function with the `def` statement, you can specify what should be returned with the `return` statement. 

`None` is a special value returned by print.  It is a lack of a value. Every function has a return value. `key word arguments` can be added to functions to change the behaviour. 

Variables inside a function can have the same name as a variable outside a function.  

* Global scope: available throughout
* Local scope: available in the function

These scopes are containers of variables.  Variables that are either *global* or *local*.  The global is created when the program starts and is destroyed when it is closed; the local is created when a function is called and destroyed when it is returned.

Local variables cannot be used in the global scope. However, local variable can use global variables.  Python will assume that the variable is local so long as it is assigned.  If you want Python to take the global variable after the name has been assigned in a function, it is necessary to use  `global xxxxx `. 

The benefit of having global and local variables is that it separates functions from the rest of the code. If something goes wrong in the function, it is confined to the function. 

##Handling errors
To stop program ending on an error, it is possible to use `try` and `except`.  This will continue in the case of an error being thrown.  See example in `error.py`

### Input validation
```
print('How many cats do you have?')
numCats = input()
try:
  if int(numCats) >= 4:
    print('That is a lot of cats')
  else: 
    print('That is not that many cats.')
except ValueError:
  print('You did not enter a number')
```

Input is validated as a number.   

# Lists
Contains multiple values in an ordered sequence. It contains items. Individual items can be taken from the list with indexation `[]`.  Also a *slice* of several values can be taken. `list` function will turn something like a string into a list.  `in` function will determine whether an item is in list (returning a boolean). `not in` is the opposite. 

One good method is to use for loops and lists.  For example, 
```
supplies = ['pens', 'penciles', 'rubber', 'board']
for i in range(len(supplies)):
  print('index' + str(i) + 'in supplies is: ' + supplies[i])
```

This allows i to be the index number and the place in the supplies list. 

###Multiple Assignment
If there is a list `cat` with items `fat`, `orange` and `loud`.  These can be assigned to other variables with 
```
size, colour, disposition = cat
```

This can be used to perform **swap variables** 

###Augmented Assignment Operators
```
spam = 42
spam = spam + 1
spam
```

is the same as 
```
spam += 1
```
# Methods
This is the same as a function but it is called on a specific value. For example, `index` is a method that will find the index of a particular list.  However, you have to call that method on the object `listname.index`.  Each data type has its own set of methods. 

To add new values to a lit use the `append()` and `insert()` methods. Methods only apply to a particular data type. `sort()` is a useful list method. Key words may change behaviour. For example, `reverse = TRUE` will change the behaviour of sort. Cannot sort strings and integers.  AscII-betical sort will put capitals before lower case. 

A list can be seen as a single character string.  Many of the functions can be used.  While strings can be index but they are immutable (cannot be changed). To change strings, there is a need to create a new string.

Immutable objects (like lists) stand alone and the list themselves just contain references to the list. Therefore, if the list is assigned to another name and a change in made in the list under that name, the list referred to by the original name will also change. Therefore, if a list is used and changed inside a function, this will also change the global value.   Immutable variables like strings and duple do not face this problem. 

A fundamental change can be made with a `deep copy`.  This is in the book. 

##Dictionaries
Like lists dictionaries contain different data types but use something other than integer for index. They are called keys. A key-value pair. 

Three methods of getting information
```
list(eggs.keys())
list(eggs.values())
list(eggs.items())
```
It is usually best to test whether key exists before trying to return its value. this will prevent an error message. 

List of methods for dictionaries 

* `dictionary.get(<what you want?, what to return if not there)`
* `setdefault()` this will set the key if it does not already exist.

## Data structures
Dictionaries are good ways of managing data. 

Look at tic-tac-toe function, 

`type` will determine object type. 

# Strings
Need double quote sometimes. 

```
"That is Alic's hat"
```
Escape characters allow the use of otherwise illegal characters. For example, 

``` 'Say hi to Bob\'s mother' ``` 

```print('Hello \nWhat is you name \nI\'m fine)```

A *raw-string* will print all the characters as they are.  For example, 

```r'This is Calva\'s cat' ```

A multi-line string can also be made with three (double) quotations. For example, 

``` 
"""Deal Alice
Eve's cat has been arrested. """ 
````
## More strings

There are a number of function

Function| Use
---|---
x.lower() | changes x to lower case
x.upper() | changes x to upper
x.islower()| Checks if x is lower case
x.isupper()| checks if x is upper case
isalpha()| letters only
isalnum()| letters and numbers only
isdecimal()| Numbers only
isspace()| Space only
istitle()| title-case only
.title()| Changes something to title
join()| Will join strings together (join can be specified)
.split()| Splits a string
ljust()| left justified (length of string and filling can be specified)
rjust()| right justified
center()| Centre
strip()| Strip (white space, or specified)
rstrip()| right strip (white space, or specified)
lstrip()| left strip (white space, or specified)
replace()| replace one string with another
paperclip.copy()|copy to clipboard (need to install paperclip)
paperclip.paste()| paste to the clipboard (need to install paperclip)

##String formatting
Insteady of catonating strings with quotes and plus, it is possible to use the *string formatting* function.  This uses `%s` for insertion. These are called *conversion specifiers*.  

#Running python from the command line
The first line of python programmes should be a *shebang* line. 

This is 

* `#! python 3` for windows
* `#! /usr/bin/env python 3` for linux

On windows press `windows key +R` to being up the *run dialog*. Type `cmd` to bring up the command prompt window. 

*Batch files* or *Script file*

Environemnt variables are set from *advanced system settings* in the *control panel*.  If the path to the folder with the batch file is specified, this will automatically search that folder for the file. This saves specifiying the whole path. 

Function arguments can be specified in the command line. 

#Regular expressions
Allow you to specify a pattern of text. Use the re module. 

There area number of functions that can be used once the `re module` has been imported

* `re-compile()` will creates a reex object
* Use raw strings `r'\d` so that the backslashes can be used
* Use `search() method to create a *matched object*.
* `group()` for the matched string
* `\d` is a numeric digit.

##Further regular expressions
It is possible to group parts of the regular expession so that when the *match object* is returned in `mo.group`, these individual components can be extracted as (for example) `mo.group[1]`

Parenthese have a special meaning in regular expresssion - they mark out where the group begins and ends. If you want to find parentheses you have to use the backslash to begin. 

`|` is the *pipe character. This can be used to match one of several expressions. For example, `batReg = re.compile(r'Bat(man|mobile|copter|bat)')`

##Syntax for number of groups

The following are useful

* `?` match the expression zero or one times (ie `Bat(wo)?man` will look for Batman or Batwoman as wo can appear or not)
* `*` mean match zero or more times. `Bat(wo)*man` will find Batwowowowowman.  
* `+` this must match at last once.  Now `Bat(wo)+man` will not find Batman. 
* `{x}` will match exactly x times. 
* `{x, y}` at least x times at most y. Leaving off one of the values will be taken as either zero or infinity. 
* Python re do *greedy matches* or the longest match so for (3, 5) it will match the 5 if it is available.  For a non-greedy match, use the `?` after like `{3, 5}?`

Further regular expression

* `search()` will find the first object
* `findall()` will find all cases (will return a string if there are zero or one group but a list if there is more than one group).  It will return groups of components in a list.  If there are three groups it returns a list of tuples. 

#Character class

* `\d` represents any numeric digit. 
* `\D` Any character thta is not a numeric digit. 
* `\w` Any letter, numberic digit or the underscore character
* `\W` Any character that is not a letter, a numeric digit or the underscore character.
* `s` Any space, tab or new line character
* `S` Any character that is not a space, tab or new line character

It is possible to make your own character classes. 

* `vowelRegex = re.compile(r'[aeiouAEIOU]') # r'(a|e|i|o|u)'
* `^` will do the opposite (it would be the consonants)
* `^` can also mean that the expression must come at the begining
* `$` says that the pattern must come at the end of the string
* `.` stands for any character except newline
* `.*` the dot-start mean it can match anything
* `.*' is *greedy*
* `*?` is *non-greedy*. 
* `.*` will match everything except a new line `\n`
* to match a everything (including new line) `re.compile(r'.*', re.DOTALL)`
* Can also use `re.IGNORECASE` will ignore case (`re.I` for short)

##Find and replace
Can use the `sub` method to substitute. 

* `namesRegex.sub('REDACTED', 'Agent Alices and Agent Bob...')`
* the sub method will find all the cases
* `namesRegex = re.complie(r'Agent (\w)\w*')` will fine the first letter after agent 
* `namesregex.sub('r'Agent \1****)` will replace the name after Agent with the first letter. This is taken from the first group. 
* verbose format will allow the regular expression to be set out over a number of line. This allows comments to make the regular expression more readable. 
* 
```
re.compile(r'''
      (\d\d\d-))|  # area code (without parentheses)
      (\(d\d\d\d) ) # or area code wtih parens and no dash
      \d\d\d # first three digits
      \d\d\d\d 
      '''# last four digits, 
      re.VERBOSE)
```      
* re.IGNORE | re.DOTALL | re.VERBOSE to use multiple options    

#Working with files and folders
Root folder is 

* C:\ on Windows
* / on linux

For python to print `\` there must be a `\` or make it *raw string* with `r`. 

*os module* containts functions 

* `os.path.join()` will join strings together to make a path in the appropriate operating-system method
* `os.sep` is the appropriate string join. 
* `os.chdir` will change the working directory
* `os.path.abspath` will return the absolute path of the file that you give it. Convert relative into absolute
* `os.path.isabs` tells you wether it is absolute path (Bolean)
* `os.path.relpath` gives the relative path to some point
* `os.path.dirname` gives the path to the file
* `os.path.basename` gives the file name and last folder
* `os.path.exists` will give a Bolean for existance of path name
* `os.path.isfile` is it is file
* `os.path.isdir` is it a path
* `os.path.getsize` gets size of the file
* `os.path.listdir` all the folders and files in a directory
* `os.makedirs` will make specified directories

##Save strings to files

* Use of plain text files. Basic information. 
* Binary files - excel etc

* ` open('c://dir/file name')`
Methods include
* `read()` reads the file
* `realines()` returns a list of strings
* `w` argument to write - overwrites an existing file 
* `a` argument to write - will add to the file
* add `\n` to create a new line
* import `shelve` module
* shelve will create a structure like a python *dictonary*
* This will create 3 binary files to store the information
* shelve can return keys and values like a dictionary

## Rename or move files and folders
`shutil` module has a range of functions that will allow renaming and moving of files and folders. Functions: 

* `shuti.copy(<from>, <to>)`
* `shuti.copy(<from>, <to>, newname)`  Add a new name. 
* `shutil.copytree(<from>, <to>)` Now whole directory is copied
* `shutil.move(<from>, <to>)`
* `shutil.move(<from>, <to>)`  to renmame, move to the same folder with a new name

##Delete files

* in the `os` module us `os.unlink(<filename)`
* `os.rmdir` can remove a folder.  This will only work if it empty
* in the `shutil` use `shutil.rmtree(<foldername>)` to remove the folder.  Must be careful.
* `send2trash` can be downloaded with pip and will send anything that is deleted to the recycle bin. 
* `send2trach.send2trach`

##Further directory actions

* `os.walk()` - pass a root folder. This will return a list of three: folder name, folders inside, files inside. 

for example, 
```
import os
for folderName, subFolder, filnames in os.walk('c:\\'):
  print('The folder is ' + folderName)
  print('The subfolders in ' + folderName + ' are: ' + str(subfolders))
  print('The filenames in ' + folderName + ' are: ' + str(filenames))
  print()
```
#Debugging
Exceptions are raised when there is a mistake.

*`raise Exception('This is an error')`

A error message is called a *traceback*.  It should provide an indication of where the error lies.  The `traceback.format_exc()` function will give a strinig of the error. This is in the `traceback` module.  The error could be sent to an error file and the exception can explain where the informationa about the error is stored. 

* Assertions.  This is a sanity check. Makes sure that there is no an issue
* `assert(<conditiion>) - something that must be true.  Aims to detect programming error.  For example, one of the trafic lights must be red. 

##Logging
This is an excellent way to understand what is happening with the programme. The `logging` module makes it easy to create a record of the custom messages that are written. Messages can be displayed on the screen. 

```
import logging
loging.basicConfig(level = logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')
```

This can be used to find a bug. This code is used to output values of i as it iterates through. This can identify problems. In the factorial programme, it shows that i = 0 and the total product is zero (therefore, need to change i to start from 1). This is similar to print, but provides a time stamp and can be exported to a log file.  Logging can also be turned off with the following.  `logging.disable(loging.CRITICAL)`

There are 5 levels of activity

* logging.debug()
* logging.info()
* logging.warning()
* logging.error()
* logging.critical()

Critical will disable all the messags.

To write to the file, in `logging.basicConfir`, write the filename to dump the infomration into.

###Debugger
It will run a single line of code one step at a time. Click on debug and debugger. Use all the information. This will show the value of each variable. There are five buttons that can be used.

* Go - run normally
* Step - move the debugger one step within the function
* Over - steps over the function to the next function
* Out - move to end
* Quit - ends programme

It is usually not necessary to step into the python code.  

*Breakpoints* can be set to force the debugger to open at a particular point. 




  